### ISSUE TITLE
Scrool bar on Configuration+Calc tab

### ISSUE THREAD

**Issue by Vilmeider** [LocalIdentity/PathOfBuilding#4130] opened 2022-02-11 10:02 UTC
### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Is your feature request related to a problem?

I have hight scale because i have low vision, after last update i cant select some option on the configuration tab
https://gyazo.com/cf937a27b131716a2f4715ad9db19c9e

### Describe the solution you'd like

Add right/left scroll bars to Configuration+Calc tab like on the Items tab

### Additional context

Thanks for your apport for the POE community

**Comment by Nightblade** [comment] 2022-02-12 06:10
Dupe of #4082 ?

**Closed as completed** 2022-02-13 17:21 UTC
