### ISSUE TITLE
Weird stuff happening with elemental ailments source name

### ISSUE THREAD

**Issue by xkomachi** [LocalIdentity/PathOfBuilding#135] opened 2020-01-20 20:26 UTC
Steps:
1. Make a new build
2. Add lightning arrow (lvl 20, 0 quality)
3. Add a suitable weapon (i.e. a bow with no ailment-related mods)
3. Level up lightning arrow (level 21). The source name for "Increased shock effect" in the calc tab changes from "lightning arrow" to "Storm Call".
4. Make the gem 20 quality. You gain chance to shock from source name "stormblast mine".

https://pastebin.com/tGQnF116 build example. 

Running fork v1.4.157.1

**Comment by xkomachi** [comment] 2020-01-21 22:41
Here's a picture of lightning arrow acting as stormblast mine: 
![a](https://user-images.githubusercontent.com/15238891/72849486-7817f200-3caf-11ea-82d9-57849bf201ad.png)

Here's another picture of stormblast mine acting as stormcall & lightning arrow:
![b](https://user-images.githubusercontent.com/15238891/72849598-b6adac80-3caf-11ea-94e1-40099564b7ba.png)
![c](https://user-images.githubusercontent.com/15238891/72849648-da70f280-3caf-11ea-919b-b3a9edddd577.png)

**Comment by Fish013** [comment] 2020-01-22 11:15
I can now reproduce it with 20/21 lightning arrow, but only in field "Chance to Shock". It is correct for me in Inc. Shock Effect

**Comment by worldendDominator** [comment] 2020-01-22 16:58
I've encountered this too. I had Lightning Tendrils linked with Faster Casting, and "inc. cast speed" field in Calcs tab said Culling Strike instead (which I also had equipped elsewhere).
This was some time ago and I've changed my gems since then, but I've reproduced it now with a Portal/L.Tendrils/F.Casting link - both Portal and Tendrils say Portal instead of Faster Casting.

**Comment by xkomachi** [comment] 2020-01-22 18:07
@worldendDominator Your cast speed says "Portal"? Mine says culling strike and **I don't have it equipped anywhere**
![a](https://user-images.githubusercontent.com/15238891/72920801-b9151280-3d52-11ea-8fb8-adfbaf01799b.png)

**Comment by Fish013** [comment] 2020-02-12 22:04
@LocalIdentity working on it

**Comment by LocalIdentity** [comment] 2020-02-25 14:28
Fixed in 1.4.157.5

**Closed by LocalIdentity** 2020-02-25 14:28 UTC
Labels: bug
