### ISSUE TITLE
Can't load attribute stacker, Mask of the Tribunal pob made in 2.7.0 pob version

### ISSUE THREAD

**Issue by kuling12345** [LocalIdentity/PathOfBuilding#3402] opened 2021-10-19 01:56 UTC
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I cdouble click on a selected premade build, I expect it to open so I can look at it and edit it

### What is the actual behaviour/value?

when I click on the saved build, it starts loading and crashed, I get an error

### How to reproduce the issue

Try loading an attribute stacker mask of the tribunal build in 3.15?

### Build code

```shell
its in the screenshot
```

### Screenshots

![Can't open mask of the tribunal pob (summoner still works)](https://user-images.githubusercontent.com/92767922/137830986-60d9f1b3-a78c-4b71-8815-d852d3221089.png)

**Comment by kuling12345** [comment] 2021-10-19 02:22
> Can you upload your build xml here?

Forgot to mention that I get 2 errors. 

First one is that there is not enough memory, and I fix that by turning on Performance mode battery settings.

The second one is in the screenshot.

https://easyupload.io/jpffqc

**Comment by SaloEater** [comment] 2021-10-19 15:59
I did testing, literally duplicate of https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/3377

**Closed as completed** 2021-10-21 08:22 UTC
Labels: bug, duplicate
