### ISSUE TITLE
Vulconus avatar of fire stays enabled

### ISSUE THREAD

**Issue by Hapseleg** [LocalIdentity/PathOfBuilding#139] opened 2020-01-21 22:41 UTC
If you equip Vulconus, enable "Do you have Avatar of Fire?" in configuration and unequip the weapon again, avatar of fire will stay enabled.

1. Equip Vulconus (unique dagger)
2. Enable "Do you have Avatar of Fire?" under configuration
3. Unequip Vulconus

Keep up the awesome work

**Comment by Fish013** [comment] 2020-01-21 23:05
Related to #105

**Comment by LocalIdentity** [comment] 2020-01-23 01:32
Duplicate of https://github.com/LocalIdentity/PathOfBuilding/issues/105

**Closed by LocalIdentity** 2020-01-23 01:32 UTC
